export const ADD_MESSAGE = "ADD_MESSAGE";

export const DELETE_MESSAGE = "DELETE_MESSAGE";

export const SET_TYPING_VALUE = "SET_TYPING_VALUE";

export const SEND_MESSAGE = "SEND_MESSAGE";

export const OPEN_THREAD = "OPEN_THREAD";

export const ADD_USER = "ADD_USER";

export const SEARCH_MESSAGE = "SEARCH_MESSAGE";

export const SAVE_MATCH_MESSAGE = "SAVE_MATCH_MESSAGE";
